### ISSUE TITLE
No puedo ejecutar paint!..

### ISSUE THREAD

**Issue by jonathanchourio** [lrusso/WinAppRunner#1]
He estado probando y no puedo ejecuttar ningun otro aplicativo, al subirlo no se ve.

pude comprobar que si subió usando la opcion de download.

https://pasteboard.co/6GRXSOxQwu5H.png

hehe!

**Comment by lrusso** [comment]
I know, it is an experimental technology, just an improvement from the original project https://github.com/danoon2/Boxedwine. I am not an Emscripten developer.
